name: CD - Pipeline de Entrega Contínua para Azure

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build e Push da Imagem Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: maxloam/connectgreen:latest

    - name: Deploy para Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'connectgreen'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ secrets.DOCKERHUB_USERNAME }}/connectgreen:latest'