name: CD - Pipeline de Entrega Contínua para Azure

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Login no Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Deploy para Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'connectgreen'
        images: 'mongo:latest'

    - name: Logout do Azure
      run: az logout