name: CI - Pipeline de Integração Contínua com Testes BDD

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: pip install -r requirements.txt

    - name: Subir containers com Docker Compose
      run: docker-compose up -d --build

    - name: Aguardar serviços iniciarem
      run: sleep 25

    - name: Executar testes Pytest-BDD
      run: pytest -v tests/step_defs/

    - name: Desligar containers
      if: always() 
      run: docker-compose down